//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarkatorGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveFile {
            get {
                return ((string)(this["SaveFile"]));
            }
            set {
                this["SaveFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArkTools {
            get {
                return ((string)(this["ArkTools"]));
            }
            set {
                this["ArkTools"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputDir {
            get {
                return ((string)(this["OutputDir"]));
            }
            set {
                this["OutputDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int MaxLevel {
            get {
                return ((int)(this["MaxLevel"]));
            }
            set {
                this["MaxLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int LevelStep {
            get {
                return ((int)(this["LevelStep"]));
            }
            set {
                this["LevelStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ { \"Group\": \"Shopping List\", \"Order\": 0.0, \"Species\": \"Allosaurus\", \"MinLevel\": " +
            "92, \"MaxLevel\": null, \"Female\": true }, { \"Group\": \"Worries\", \"Order\": 175.0, \"S" +
            "pecies\": \"Alpha Carnotaurus\", \"MinLevel\": 100, \"MaxLevel\": null, \"Female\": null " +
            "}, { \"Group\": \"Worries\", \"Order\": 50.0, \"Species\": \"Alpha Leedsichthys\", \"MinLev" +
            "el\": null, \"MaxLevel\": null, \"Female\": null }, { \"Group\": \"Worries\", \"Order\": 12" +
            "5.0, \"Species\": \"Alpha Megalodon\", \"MinLevel\": 100, \"MaxLevel\": null, \"Female\": " +
            "null }, { \"Group\": \"Worries\", \"Order\": 192.1875, \"Species\": \"Alpha Mosasaur\", \"M" +
            "inLevel\": null, \"MaxLevel\": null, \"Female\": null }, { \"Group\": \"Worries\", \"Order" +
            "\": 287.5, \"Species\": \"Alpha Raptor\", \"MinLevel\": 100, \"MaxLevel\": null, \"Female\"" +
            ": null }, { \"Group\": \"Worries\", \"Order\": 443.75, \"Species\": \"Alpha T-Rex\", \"MinL" +
            "evel\": 100, \"MaxLevel\": null, \"Female\": null }, { \"Group\": \"Worries\", \"Order\": 5" +
            "21.875, \"Species\": \"Giganotosaurus\", \"MinLevel\": null, \"MaxLevel\": null, \"Female" +
            "\": null }, { \"Group\": \"Worries\", \"Order\": 610.9375, \"Species\": \"Titanosaur\", \"Mi" +
            "nLevel\": null, \"MaxLevel\": null, \"Female\": null }, { \"Group\": \"Shopping List\", \"" +
            "Order\": 87.5, \"Species\": \"Baryonyx\", \"MinLevel\": 100, \"MaxLevel\": null, \"Female\"" +
            ": null }, { \"Group\": \"Shopping List\", \"Order\": 200.0, \"Species\": \"Dire Bear\", \"M" +
            "inLevel\": 100, \"MaxLevel\": null, \"Female\": null }, { \"Group\": \"Worries\", \"Order\"" +
            ": 292.1875, \"Species\": \"Diseased Leech\", \"MinLevel\": null, \"MaxLevel\": null, \"Fe" +
            "male\": null }, { \"Group\": \"Shopping List\", \"Order\": 300.0, \"Species\": \"Quetzal\"," +
            " \"MinLevel\": null, \"MaxLevel\": null, \"Female\": null }, { \"Group\": \"Shopping List" +
            "\", \"Order\": 419.921875, \"Species\": \"Rex\", \"MinLevel\": 100, \"MaxLevel\": null, \"Fe" +
            "male\": null }, { \"Group\": \"Shopping List\", \"Order\": 510.9375, \"Species\": \"Yutyra" +
            "nnus\", \"MinLevel\": 84, \"MaxLevel\": null, \"Female\": null } ]")]
        public string SavedSearches {
            get {
                return ((string)(this["SavedSearches"]));
            }
            set {
                this["SavedSearches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10000")]
        public double MainWindowLeft {
            get {
                return ((double)(this["MainWindowLeft"]));
            }
            set {
                this["MainWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10000")]
        public double MainWindowTop {
            get {
                return ((double)(this["MainWindowTop"]));
            }
            set {
                this["MainWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1352")]
        public double MainWindowWidth {
            get {
                return ((double)(this["MainWindowWidth"]));
            }
            set {
                this["MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double MainWindowHeight {
            get {
                return ((double)(this["MainWindowHeight"]));
            }
            set {
                this["MainWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int ConvertDelay {
            get {
                return ((int)(this["ConvertDelay"]));
            }
            set {
                this["ConvertDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int ListFontSize {
            get {
                return ((int)(this["ListFontSize"]));
            }
            set {
                this["ListFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double PinScale {
            get {
                return ((double)(this["PinScale"]));
            }
            set {
                this["PinScale"] = value;
            }
        }
    }
}
